// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfVD_ZpAveFx2DzBGplmfa9VetDa86kz8',
    appId: '1:594646811375:web:898053ef9cd89096ea511a',
    messagingSenderId: '594646811375',
    projectId: 'book-swap-app2',
    authDomain: 'book-swap-app2.firebaseapp.com',
    storageBucket: 'book-swap-app2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL2rTo3JK1OXeoAMDYRTit7TlnHIZfjVE',
    appId: '1:594646811375:android:7d31d5f3159dc686ea511a',
    messagingSenderId: '594646811375',
    projectId: 'book-swap-app2',
    storageBucket: 'book-swap-app2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC5z0Xi58bfsgWuKy-3kt-OupiS_XpV7g',
    appId: '1:594646811375:ios:8936357363f2da62ea511a',
    messagingSenderId: '594646811375',
    projectId: 'book-swap-app2',
    storageBucket: 'book-swap-app2.firebasestorage.app',
    iosBundleId: 'com.example.bookSwapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC5z0Xi58bfsgWuKy-3kt-OupiS_XpV7g',
    appId: '1:594646811375:ios:8936357363f2da62ea511a',
    messagingSenderId: '594646811375',
    projectId: 'book-swap-app2',
    storageBucket: 'book-swap-app2.firebasestorage.app',
    iosBundleId: 'com.example.bookSwapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfVD_ZpAveFx2DzBGplmfa9VetDa86kz8',
    appId: '1:594646811375:web:dbd2026c84bbbb96ea511a',
    messagingSenderId: '594646811375',
    projectId: 'book-swap-app2',
    authDomain: 'book-swap-app2.firebaseapp.com',
    storageBucket: 'book-swap-app2.firebasestorage.app',
  );

}