// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMaesAwbkdiQnbuJR2Oaxm-hjdThyUBz8',
    appId: '1:731412522113:web:2a495228a2f611fed11980',
    messagingSenderId: '731412522113',
    projectId: 'book-swap-app-1673e',
    authDomain: 'book-swap-app-1673e.firebaseapp.com',
    storageBucket: 'book-swap-app-1673e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP7yNbhX68gM8t78sCj6c7o-PfUlt0fJw',
    appId: '1:731412522113:android:c8dc0b7aeb39b621d11980',
    messagingSenderId: '731412522113',
    projectId: 'book-swap-app-1673e',
    storageBucket: 'book-swap-app-1673e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCSpuWu_OO12MIT8h8W4PvIBxhO36Du7Q',
    appId: '1:731412522113:ios:cccbd5e46aa1c9bcd11980',
    messagingSenderId: '731412522113',
    projectId: 'book-swap-app-1673e',
    storageBucket: 'book-swap-app-1673e.firebasestorage.app',
    iosBundleId: 'com.example.bookSwapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCSpuWu_OO12MIT8h8W4PvIBxhO36Du7Q',
    appId: '1:731412522113:ios:cccbd5e46aa1c9bcd11980',
    messagingSenderId: '731412522113',
    projectId: 'book-swap-app-1673e',
    storageBucket: 'book-swap-app-1673e.firebasestorage.app',
    iosBundleId: 'com.example.bookSwapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMaesAwbkdiQnbuJR2Oaxm-hjdThyUBz8',
    appId: '1:731412522113:web:fac1344efa7a1490d11980',
    messagingSenderId: '731412522113',
    projectId: 'book-swap-app-1673e',
    authDomain: 'book-swap-app-1673e.firebaseapp.com',
    storageBucket: 'book-swap-app-1673e.firebasestorage.app',
  );
}
